restart_file: ccre-2023-04-13-test_runS3.nc
start_datetime: 2023-04-12 00:00:00
forecast_start_datetime: 2023-04-14 00:00:00
end_datetime: .na.character
forecast_horizon: 16.0
sim_name: test_runS3
configure_flare: configure_flare.yml
use_s3: yes
