restart_file: .na
start_datetime: 2024-01-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2024-02-22 00:00:00
forecast_horizon: glm_flare_v1
sim_name: test_runS3
configure_flare: configure_flare.yml
use_s3: TRUE

