restart_file: .na
start_datetime: 2022-11-20 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-12-01 00:00:00
forecast_horizon: 32.0
sim_name: glm_flare_reforecast
configure_flare: configure_flare.yml
use_s3: TRUE

