s3:
  drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/met/gefs-v12
  inflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow/ccre/lm_ar
  outflow_drivers:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/drivers/inflow/ccre/lm_ar
  targets:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/targets/ccre
  forecasts:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/netcdf
  forecasts_parquet:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/forecasts/parquet
  restart:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/restart
  scores:
    endpoint: renc.osn.xsede.org
    bucket: bio230121-bucket01/flare/scores/parquet
location:
   site_id: ccre
   name: Carvins Cove Reservoir
   latitude: 37.3697  #Degrees North
   longitude: -79.9580  #Degrees West
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  256
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: ccre-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3.nml
   max_model_layers: 75
   modeled_depths: [0.00,0.25,0.50,0.75,
                    1.00,1.25,1.50,1.75,
                    2.00,2.25,2.50,2.75,
                    3.00,3.25,3.50,3.75,
                    4.00,4.25,4.50,4.75,
                    5.00,5.25,5.50,5.75,
                    6.00,6.25,6.50,6.75,
                    7.00,7.25,7.50,7.75,  
                    8.00,8.25,8.50,8.75,
                    9.00,9.25,9.50,9.75, 
                    10.00,10.25,10.50,10.75, 
                    11.00,11.25,11.50,11.75, 
                    12.00,12.25,12.50,12.75, 
                    13.00,13.25,13.50,13.75, 
                    14.00,14.25,14.50,14.75, 
                    15.00,15.25,15.50,15.75, 
                    16.00,16.25,16.50,16.75, 
                    17.00,17.25,17.50,17.75, 
                    18.00,18.25,18.50,18.75, 
                    19.00,19.25,19.50,19.75,
                    20.00,20.25,20.50,20.75, 
                    21.00]
   par_config_file: parameter_calibration_config.csv
   obs_config_file: observations_config.csv
   states_config_file: states_config.csv
   depth_model_sd_config_file: depth_model_sd.csv
default_init:
   lake_depth: 22.8  #not a modeled state
   temp: [20,20,20,20,20,20,
          20,20,20,20,20,20,20,20]
   temp_depths: [0.1,1.0,2.0,3.0,4.0,5.0, 
                 6.0,7.0,8.0,9.0,10.0,11.0,15.0,19.0]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   include_outflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: NA
   observed_inflow_filename: NA
   inflow_variables: NA
   use_ler_vars: FALSE
   historical_inflow_model: .na
   future_inflow_model: .na
   historic_outflow_model: .na
   future_outflow_model: .na
   local_inflow_directory: .na
   local_outflow_directory: .na
   use_flows_s3: .na
met:
   future_met_model: 'stage2'
   historical_met_model: 'stage3'
   historical_met_use_s3: TRUE
   future_met_use_s3: TRUE
   use_openmeteo: FALSE
   local_met_directory: 'drivers'
   use_forecasted_met: TRUE
   #   use_observed_met: FALSE
   #   local_directory: .na
   #   observed_met_filename: .na
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   met_downscale: TRUE
   inflow: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter]
   generate_plots: FALSE
